[tools]
node = "24"
pnpm = "latest"

[tasks.build]
description = "Build"
run = "rm -rf out && pnpm run compile && pnpm run esbuild-base"

[tasks."build:prod"]
description = "Build production"
run = "rm -rf out && pnpm run compile && pnpm run esbuild-prod"

[tasks.test]
description = "Run tests"
run = "pnpm exec vitest run"
depends = ["build"]

[tasks.lint]
description = "Run lint"
run = "pnpm run lint"

[tasks.package]
description = "Package VS Code extension (development)"
run = """
  TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
  pnpm exec vsce package --no-dependencies --out out/emily.vsix --no-yarn --no-git-tag-version --no-update-package-json "1.0.0-$TIMESTAMP"
"""
depends = ["build"]

[tasks."package:prod"]
description = "Package VS Code extension with minification (production)"
run = "pnpm exec vsce package --no-dependencies --out out/emily.vsix --no-yarn --no-git-tag-version --no-update-package-json"
depends = ["build:prod"]

[tasks."install:code"]
description = "Install VS Code extension"
run = "code --install-extension out/emily.vsix"
depends = ["package"]

[tasks."install:cursor"]
description = "Install Cursor extension"
run = "cursor --install-extension out/emily.vsix"
depends = ["package"]
