[tools]
node = "24"
pnpm = "latest"

[tasks.build]
description = "Build"
run = "pnpm run compile"

[tasks.test]
description = "Run tests"
run = "pnpm run test"
depends = ["build"]

[tasks.lint]
description = "Run lint"
run = "pnpm run lint"

[tasks.package]
description = "Package VS Code extension"
run = "pnpm exec vsce package --no-yarn --no-git-tag-version --out out/"
depends = ["build"]

[tasks."install:code"]
description = "Install VS Code extension"
run = "code --install-extension out/emily-1.0.0.vsix"
depends = ["package"]

[tasks."install:cursor"]
description = "Install Cursor extension"
run = "cursor --install-extension out/emily-1.0.0.vsix"
depends = ["package"]
