name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac

      - name: Install Node.js and pnpm via mise
        run: |
          mise install

      - name: Install dependencies
        run: mise exec -- pnpm install --frozen-lockfile

      - name: Test
        run: mise run test

      - name: Lint code
        run: mise run lint
