name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@61c1bfbed63c70a82ff0ce3301bde41875b17844

      - name: Install Node.js and pnpm via mise
        run: |
          mise install

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(mise exec pnpm -- store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: mise exec pnpm -- install --frozen-lockfile

      - name: Test
        run: mise run test

      - name: Lint code
        run: mise run lint
