name: Release VS Code Extension (Stable)

# This workflow creates stable VSIX packages and GitHub releases.
# It does NOT publish to the VS Code Marketplace.
# For development builds, see the "Build VSIX (Development)" workflow.

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac

      - name: Install Node.js and pnpm via mise
        run: |
          mise install

      - name: Install dependencies
        run: mise exec -- pnpm install --frozen-lockfile

      - name: Test
        run: mise run test

      - name: Lint code
        run: mise run lint

      - name: Package extension
        run: mise run package:prod

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          files: |
            out/emily.vsix
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
